name: Wake Up Streamlit App

on:
  schedule:
    # 這裡的 '0 */4 * * *' 代表每 4 小時整點執行一次
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Streamlit
        run: |
          curl -I https://你的專案連結.streamlit.app
